### PR TITLE
Fix #129 ConcurrentModificationException in `OtelTraceService$RunSpans.toString()`

### LINKED ISSUE #129: Intermittent java.util.ConcurrentModificationException
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.263.1
OS: Windows Server 2016 - 10.0
---
opentelemetry:0.13
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
- Windows Server 2016 - 10.0
- Linux - 4.14.200-155.322.amzn2.x86_64
```

### Results

Actual result:

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.AbstractMap.toString(Unknown Source)
	at com.google.common.collect.AbstractMapBasedMultimap$AsMap.toString(AbstractMapBasedMultimap.java:1323)
	at com.google.common.collect.AbstractMultimap.toString(AbstractMultimap.java:253)
	at com.google.common.collect.ArrayListMultimap.toString(ArrayListMultimap.java:65)
	at java.lang.String.valueOf(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService$RunSpans.toString(OtelTraceService.java:244)
	at java.lang.String.valueOf(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService.lambda$getSpan$1(OtelTraceService.java:81)
	at java.util.logging.Logger.log(Unknown Source)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService.getSpan(OtelTraceService.java:81)
	at io.jenkins.plugins.opentelemetry.job.OtelEnvironmentContributor.buildEnvironmentFor(OtelEnvironmentContributor.java:26)
	at hudson.model.Run.getEnvironment(Run.java:2442)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getEnvironment(WorkflowRun.java:492)
	at hudson.plugins.git.GitSCM.getParamExpandedRepos(GitSCM.java:504)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1205)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1301)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Fix https://github.com/jenkinsci/opentelemetry-plugin/issues/129

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.util.AbstractMap.toString(Unknown Source)
	at com.google.common.collect.AbstractMapBasedMultimap$AsMap.toString(AbstractMapBasedMultimap.java:1323)
	at com.google.common.collect.AbstractMultimap.toString(AbstractMultimap.java:253)
	at com.google.common.collect.ArrayListMultimap.toString(ArrayListMultimap.java:65)
	at java.lang.String.valueOf(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService$RunSpans.toString(OtelTraceService.java:244)
	at java.lang.String.valueOf(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService.lambda$getSpan$1(OtelTraceService.java:81)
	at java.util.logging.Logger.log(Unknown Source)
	at io.jenkins.plugins.opentelemetry.job.OtelTraceService.getSpan(OtelTraceService.java:81)
	at io.jenkins.plugins.opentelemetry.job.OtelEnvironmentContributor.buildEnvironmentFor(OtelEnvironmentContributor.java:26)
	at hudson.model.Run.getEnvironment(Run.java:2442)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getEnvironment(WorkflowRun.java:492)
	at hudson.plugins.git.GitSCM.getParamExpandedRepos(GitSCM.java:504)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1205)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1301)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

### CODE REVIEW

**Review by v1v — APPROVED** [review]

File: src/main/java/io/jenkins/plugins/opentelemetry/job/OtelTraceService.java [hunk 1]
```diff
@@ -241,9 +241,11 @@ public Tracer getTracer() {
 
         @Override
         public String toString() {
+            // clone the Multimap to prevent a ConcurrentModificationException
+            // see https://github.com/jenkinsci/opentelemetry-plugin/issues/129
             return "RunSpans{" +
-                    "runPhasesSpans=" + runPhasesSpans +
-                    ", pipelineStepSpansByFlowNodeId=" + pipelineStepSpansByFlowNodeId +
+                    "runPhasesSpans=" + new ArrayList(runPhasesSpans) +
```
Comment (kuisathaverat) [inline src/main/java/io/jenkins/plugins/opentelemetry/job/OtelTraceService.java:247]: This list will not need to modify, it is possible to use an unmodifiableList list

```suggestion
                    "runPhasesSpans=" + Collections.unmodifiableList(runPhasesSpans) +
```

**Review by kuisathaverat — APPROVED** [review]
